import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'app-pizza-hut';

  displayedColumns: string[] = ['numero', 'ubicacion', 'clientes', 'edad', 'genero', 'consumo', 'precio', 'tiempo', 'tipoPago', 'medio',];


  ELEMENT_DATA: any[] = [
    {
      "numero": 1,
      "ubicacion": "Mega plaza",
      "clientes": "Juan Pérez García",
      "edad": "25 años",
      "genero": "Maculino",
      "consumo": "Pizza mediana (americana)",
      "precio": "20 soles",
      "tiempo": "17 minutos",
      "tipoPago": "Tarjeta de crédito Visa",
      "medio": "Periódicos en línea"
    },
    {
      "numero": 2,
      "ubicacion": "Plaza norte",
      "clientes": "Ana Rodríguez Martínez",
      "edad": "34 años",
      "genero": "Femenino",
      "consumo": "Pizza mediana (americana)",
      "precio": "20 soles",
      "tiempo": "12 minutos",
      "tipoPago": "Tarjeta de crédito MasterCard",
      "medio": "Revistas"
    },
    {
      "numero": 3,
      "ubicacion": "Mall del Sur",
      "clientes": "Luis González López",
      "edad": "41 años",
      "genero": "Maculino",
      "consumo": "Pizza familiar (hawaiana)",
      "precio": "45 soles",
      "tiempo": "22 minutos",
      "tipoPago": "Tarjeta de débito Visa",
      "medio": "Bolantes"
    },
    {
      "numero": 4,
      "ubicacion": "Plaza San Miguel",
      "clientes": "María Martínez Sánchez",
      "edad": "59 años",
      "genero": "Femenino",
      "consumo": "Pizza mediana (peperoni)",
      "precio": "20 soles",
      "tiempo": "20 minutos",
      "tipoPago": "Tarjeta de débito MasterCard",
      "medio": "Televisión"
    },
    {
      "numero": 5,
      "ubicacion": "Jockey plaza",
      "clientes": "Carlos López Ramírez",
      "edad": "22 años",
      "genero": "Masculino",
      "consumo": "Pizza mediana (americana)",
      "precio": "20 soles",
      "tiempo": "11 minutos",
      "tipoPago": "PayPal",
      "medio": "Radio"
    },
    {
      "numero": 6,
      "ubicacion": "Mall plaza",
      "clientes": "Laura González Fernández",
      "edad": "47 años",
      "genero": "Femenino",
      "consumo": "Pizza mediana (americana)",
      "precio": "20 soles",
      "tiempo": "13 minutos",
      "tipoPago": "efectivo",
      "medio": "Sitios web de noticias"
    },
    {
      "numero": 7,
      "ubicacion": "Mega plaza",
      "clientes": "Sergio Fernández Pérez",
      "edad": "28 años",
      "genero": "Masculino",
      "consumo": "Pizza familiar (hawaiana)",
      "precio": "45 soles",
      "tiempo": "25 minutos",
      "tipoPago": "yape",
      "medio": "Redes sociales (por ejemplo, Facebook, Twitter)"
    },
    {
      "numero": 8,
      "ubicacion": "Plaza norte",
      "clientes": "Isabel Torres Rodríguez",
      "edad": "63 años",
      "genero": "Femenino",
      "consumo": "Pizza mediana (americana)",
      "precio": "20 soles",
      "tiempo": "23 minutos",
      "tipoPago": "plin",
      "medio": "Bolantes"
    },
    {
      "numero": 9,
      "ubicacion": "Mall del Sur",
      "clientes": "Andrés Ramírez González",
      "edad": "37 años",
      "genero": "Maculino",
      "consumo": "Pizza mediana (peperoni)",
      "precio": "20 soles",
      "tiempo": "10 minutos",
      "tipoPago": "Tarjeta de crédito MasterCard",
      "medio": "Televisión"
    },
    {
      "numero": 10,
      "ubicacion": "Plaza San Miguel",
      "clientes": "Carmen Sánchez López",
      "edad": "55 años",
      "genero": "Femenino",
      "consumo": "Pizza familiar (peperoni)",
      "precio": "40 soles",
      "tiempo": "22 minutos",
      "tipoPago": "Tarjeta de débito Visa",
      "medio": "Radio"
    },
    {
      "numero": 11,
      "ubicacion": "Jockey plaza",
      "clientes": "Diego Romero Pérez",
      "edad": "31 años",
      "genero": "Maculino",
      "consumo": "Pizza familiar (hawaiana)",
      "precio": "45 soles",
      "tiempo": "19 minutos",
      "tipoPago": "Tarjeta de débito MasterCard",
      "medio": "Periódicos en línea"
    },
    {
      "numero": 12,
      "ubicacion": "Mall plaza",
      "clientes": "Paula Herrera García",
      "edad": "42 años",
      "genero": "Femenino",
      "consumo": "Pizza mediana (peperoni)",
      "precio": "20 soles",
      "tiempo": "22 minutos",
      "tipoPago": "PayPal",
      "medio": "Revistas"
    },
    {
      "numero": 13,
      "ubicacion": "Plaza San Miguel",
      "clientes": "Javier Díaz Martínez",
      "edad": "60 años",
      "genero": "Maculino",
      "consumo": "Pizza mediana (americana)",
      "precio": "20 soles",
      "tiempo": "21minutos",
      "tipoPago": "efectivo",
      "medio": "Bolantes"
    },
    {
      "numero": 14,
      "ubicacion": "Jockey plaza",
      "clientes": "Patricia Cruz Rodríguez",
      "edad": "24 años",
      "genero": "Femenino",
      "consumo": "Pizza familiar (hawaiana)",
      "precio": "45 soles",
      "tiempo": "10 minutos",
      "tipoPago": "yape",
      "medio": "Televisión"
    },
    {
      "numero": 15,
      "ubicacion": "Mall plaza",
      "clientes": "Francisco Vargas López",
      "edad": "53 años",
      "genero": "Maculino",
      "consumo": "Pizza familiar (peperoni)",
      "precio": "40 soles",
      "tiempo": "25 minutos",
      "tipoPago": "Tarjeta de crédito MasterCard",
      "medio": "Radio"
    },
    {
      "numero": 16,
      "ubicacion": "Mega plaza",
      "clientes": "Elena Morales Pérez",
      "edad": "45 años",
      "genero": "Femenino",
      "consumo": "Pizza familiar (peperoni)",
      "precio": "40 soles",
      "tiempo": "22 minutos",
      "tipoPago": "Tarjeta de débito Visa",
      "medio": "Sitios web de noticias"
    },
    {
      "numero": 17,
      "ubicacion": "Plaza norte",
      "clientes": "Gabriel Ortega González",
      "edad": "50 años",
      "genero": "Masculino",
      "consumo": "Pizza familiar (peperoni)",
      "precio": "40 soles",
      "tiempo": "25 minutos",
      "tipoPago": "Tarjeta de débito MasterCard",
      "medio": "Redes sociales (por ejemplo, Facebook, Twitter)"
    },
    {
      "numero": 18,
      "ubicacion": "Mall del Sur",
      "clientes": "Raquel Jiménez López",
      "edad": "29 años",
      "genero": "Femenino",
      "consumo": "Pizza mediana (peperoni)",
      "precio": "20 soles",
      "tiempo": "12 minutos",
      "tipoPago": "PayPal",
      "medio": "Televisión"
    },
    {
      "numero": 19,
      "ubicacion": "Plaza San Miguel",
      "clientes": "Pedro Ruiz García",
      "edad": "68 años",
      "genero": "Masculino",
      "consumo": "Pizza mediana (peperoni)",
      "precio": "20 soles",
      "tiempo": "10 minutos",
      "tipoPago": "efectivo",
      "medio": "Radio"
    },
    {
      "numero": 20,
      "ubicacion": "Jockey plaza",
      "clientes": "Marta Castro Rodríguez",
      "edad": "19 años",
      "genero": "Femenino",
      "consumo": "Pizza mediana (hawaiana)",
      "precio": "26 soles",
      "tiempo": "23 minutos",
      "tipoPago": "yape",
      "medio": "Periódicos en línea"
    },
    {
      "numero": 21,
      "ubicacion": "Plaza norte",
      "clientes": "Manuel Medina Sánchez",
      "edad": "48 años",
      "genero": "Maculino",
      "consumo": "Pizza mediana (americana)",
      "precio": "20 soles",
      "tiempo": "13 minutos",
      "tipoPago": "plin",
      "medio": "Revistas"
    },
    {
      "numero": 22,
      "ubicacion": "Mall del Sur",
      "clientes": "Sandra Reyes López",
      "edad": "36 años",
      "genero": "Femenino",
      "consumo": "Pizza familiar (hawaiana)",
      "precio": "45 soles",
      "tiempo": "22 minutos",
      "tipoPago": "Tarjeta de débito MasterCard",
      "medio": "Bolantes"
    },
    {
      "numero": 23,
      "ubicacion": "Plaza San Miguel",
      "clientes": "Alejandro Mendoza García",
      "edad": "71 años",
      "genero": "Maculino",
      "consumo": "Pizza mediana (hawaiana)",
      "precio": "26 soles",
      "tiempo": "21 minutos",
      "tipoPago": "PayPal",
      "medio": "Periódicos en línea"
    },
    {
      "numero": 24,
      "ubicacion": "Jockey plaza",
      "clientes": "Victoria Silva Rodríguez",
      "edad": "27 años",
      "genero": "Femenino",
      "consumo": "Pizza mediana (peperoni)",
      "precio": "20 soles",
      "tiempo": "11 minutos",
      "tipoPago": "efectivo",
      "medio": "Revistas"
    },
    {
      "numero": 25,
      "ubicacion": "Mall plaza",
      "clientes": "Raúl Montes Pérez",
      "edad": "66 años",
      "genero": "Maculino",
      "consumo": "Pizza mediana (peperoni)",
      "precio": "20 soles",
      "tiempo": "17 minutos",
      "tipoPago": "yape",
      "medio": "Bolantes"
    },
    {
      "numero": 26,
      "ubicacion": "Plaza San Miguel",
      "clientes": "Natalia Paredes Martínez",
      "edad": "40 años",
      "genero": "Femenino",
      "consumo": "Pizza familiar (peperoni)",
      "precio": "40 soles",
      "tiempo": "22 minutos",
      "tipoPago": "Tarjeta de crédito MasterCard",
      "medio": "Televisión"
    },
    {
      "numero": 27,
      "ubicacion": "Jockey plaza",
      "clientes": "Guillermo Guzmán López",
      "edad": "56 años",
      "genero": "Maculino",
      "consumo": "Pizza mediana (hawaiana)",
      "precio": "26 soles",
      "tiempo": "25 minutos",
      "tipoPago": "Tarjeta de débito Visa",
      "medio": "Radio"
    },
    {
      "numero": 28,
      "ubicacion": "Mall plaza",
      "clientes": "Adriana Rosales García",
      "edad": "38 años",
      "genero": "Femenino",
      "consumo": "Pizza mediana (hawaiana)",
      "precio": "26 soles",
      "tiempo": "19 minutos",
      "tipoPago": "Tarjeta de débito MasterCard",
      "medio": "Sitios web de noticias"
    },
    {
      "numero": 29,
      "ubicacion": "Mega plaza",
      "clientes": "Esteban Herrera Martínez",
      "edad": "57 años",
      "genero": "Masculino",
      "consumo": "Pizza familiar (peperoni)",
      "precio": "40 soles",
      "tiempo": "22 minutos",
      "tipoPago": "Tarjeta de débito Visa",
      "medio": "Redes sociales (por ejemplo, Facebook, Twitter)"
    },
    {
      "numero": 30,
      "ubicacion": "Plaza norte",
      "clientes": "Beatriz Gómez Sánchez",
      "edad": "30 años",
      "genero": "Femenino",
      "consumo": "Pizza familiar (peperoni)",
      "precio": "40 soles",
      "tiempo": "10 minutos",
      "tipoPago": "Tarjeta de débito MasterCard",
      "medio": "Revistas"
    },
    {
      "numero": 31,
      "ubicacion": "Mall del Sur",
      "clientes": "Rodrigo Núñez López",
      "edad": "62 años",
      "genero": "Masculino",
      "consumo": "Pizza mediana (hawaiana)",
      "precio": "26 soles",
      "tiempo": "23 minutos",
      "tipoPago": "PayPal",
      "medio": "Bolantes"
    },
    {
      "numero": 32,
      "ubicacion": "Plaza San Miguel",
      "clientes": "Carolina Delgado Rodríguez",
      "edad": "35 años",
      "genero": "Femenino",
      "consumo": "Pizza familiar (peperoni)",
      "precio": "40 soles",
      "tiempo": "20 minutos",
      "tipoPago": "efectivo",
      "medio": "Periódicos en línea"
    },
    {
      "numero": 33,
      "ubicacion": "Jockey plaza",
      "clientes": "Pablo Valenzuela García",
      "edad": "64 años",
      "genero": "Maculino",
      "consumo": "Pizza mediana (hawaiana)",
      "precio": "26 soles",
      "tiempo": "13 minutos",
      "tipoPago": "yape",
      "medio": "Revistas"
    },
    {
      "numero": 34,
      "ubicacion": "Mall plaza",
      "clientes": "Martina Ríos López",
      "edad": "43 años",
      "genero": "Femenino",
      "consumo": "Pizza familiar (hawaiana)",
      "precio": "45 soles",
      "tiempo": "21 minutos",
      "tipoPago": "plin",
      "medio": "Bolantes"
    },
    {
      "numero": 35,
      "ubicacion": "Mega plaza",
      "clientes": "Antonio Bravo Sánchez",
      "edad": "51 años",
      "genero": "Maculino",
      "consumo": "Pizza familiar (hawaiana)",
      "precio": "45 soles",
      "tiempo": "25 minutos",
      "tipoPago": "efectivo",
      "medio": "Periódicos en línea"
    },
    {
      "numero": 36,
      "ubicacion": "Plaza norte",
      "clientes": "Sofía Flores Rodríguez",
      "edad": "33 años",
      "genero": "Femenino",
      "consumo": "Pizza familiar (hawaiana)",
      "precio": "45 soles",
      "tiempo": "22 minutos",
      "tipoPago": "yape",
      "medio": "Revistas"
    },
    {
      "numero": 37,
      "ubicacion": "Mall del Sur",
      "clientes": "Rafael Torres García",
      "edad": "67 años",
      "genero": "Maculino",
      "consumo": "Pizza familiar (peperoni)",
      "precio": "40 soles",
      "tiempo": "12 minutos",
      "tipoPago": "plin",
      "medio": "Bolantes"
    },
    {
      "numero": 38,
      "ubicacion": "Plaza San Miguel",
      "clientes": "Valentina Vega Martínez",
      "edad": "21 años",
      "genero": "Femenino",
      "consumo": "Pizza familiar (hawaiana)",
      "precio": "45 soles",
      "tiempo": "10 minutos",
      "tipoPago": "Tarjeta de débito MasterCard",
      "medio": "Televisión"
    },
    {
      "numero": 39,
      "ubicacion": "Jockey plaza",
      "clientes": "Jaime Soto López",
      "edad": "58 años",
      "genero": "Maculino",
      "consumo": "Pizza mediana (hawaiana)",
      "precio": "26 soles",
      "tiempo": "25 minutos",
      "tipoPago": "PayPal",
      "medio": "Radio"
    },
    {
      "numero": 40,
      "ubicacion": "Mall plaza",
      "clientes": "Silvia Castro Rodríguez",
      "edad": "46 años",
      "genero": "Femenino",
      "consumo": "Pizza familiar (peperoni)",
      "precio": "40 soles",
      "tiempo": "17 minutos",
      "tipoPago": "efectivo",
      "medio": "Sitios web de noticias"
    },
    {
      "numero": 41,
      "ubicacion": "Plaza San Miguel",
      "clientes": "Lucas Martínez Pérez",
      "edad": "52 años",
      "genero": "Masculino",
      "consumo": "Pizza mediana (hawaiana)",
      "precio": "26 soles",
      "tiempo": "23 minutos",
      "tipoPago": "Tarjeta de crédito Visa",
      "medio": "Redes sociales (por ejemplo, Facebook, Twitter)"
    },
    {
      "numero": 42,
      "ubicacion": "Jockey plaza",
      "clientes": "Mariana Pérez López",
      "edad": "32 años",
      "genero": "Femenino",
      "consumo": "Pizza mediana (hawaiana)",
      "precio": "26 soles",
      "tiempo": "11 minutos",
      "tipoPago": "Tarjeta de crédito MasterCard",
      "medio": "Revistas"
    },
    {
      "numero": 43,
      "ubicacion": "Mall plaza",
      "clientes": "Bruno Ramírez García",
      "edad": "61 años",
      "genero": "Masculino",
      "consumo": "Pizza familiar (peperoni)",
      "precio": "40 soles",
      "tiempo": "19 minutos",
      "tipoPago": "Tarjeta de débito Visa",
      "medio": "Periódicos en línea"
    },
    {
      "numero": 44,
      "ubicacion": "Mall plaza",
      "clientes": "Susana Rodríguez Sánchez",
      "edad": "26 años",
      "genero": "Femenino",
      "consumo": "Pizza familiar (hawaiana)",
      "precio": "45 soles",
      "tiempo": "22 minutos",
      "tipoPago": "Tarjeta de débito MasterCard",
      "medio": "Revistas"
    },
    {
      "numero": 45,
      "ubicacion": "Mega plaza",
      "clientes": "Guillermo Flores López",
      "edad": "54 años",
      "genero": "Maculino",
      "consumo": "Pizza familiar (peperoni)",
      "precio": "40 soles",
      "tiempo": "10 minutos",
      "tipoPago": "PayPal",
      "medio": "Bolantes"
    },
    {
      "numero": 46,
      "ubicacion": "Plaza norte",
      "clientes": "Valeria González Martínez",
      "edad": "49 años",
      "genero": "Femenino",
      "consumo": "Pizza familiar (hawaiana)",
      "precio": "45 soles",
      "tiempo": "22 minutos",
      "tipoPago": "efectivo",
      "medio": "Televisión"
    },
    {
      "numero": 47,
      "ubicacion": "Mall del Sur",
      "clientes": "Raúl Mendoza García",
      "edad": "44 años",
      "genero": "Maculino",
      "consumo": "Pizza mediana (hawaiana)",
      "precio": "26 soles",
      "tiempo": "20 minutos",
      "tipoPago": "yape",
      "medio": "Radio"
    },
    {
      "numero": 48,
      "ubicacion": "Plaza San Miguel",
      "clientes": "Clara Sánchez Rodríguez",
      "edad": "39 años",
      "genero": "Femenino",
      "consumo": "Pizza familiar (hawaiana)",
      "precio": "45 soles",
      "tiempo": "25 minutos",
      "tipoPago": "plin",
      "medio": "Sitios web de noticias"
    }
  ]

  dataSource: any;

  constructor() {
    this.dataSource = this.ELEMENT_DATA;

  }
}
